### ISSUE TITLE
Help getting it working in Unreal

### ISSUE THREAD

**Issue by Besjan** [kym0761/UnrealEngine_BluetoothPlugin#1]
Hi @kym0761 
Thank you for the code.

I'm trying to get it working in Unreal, but I'm not sure if it's even recognizing the device.

I have a "wahoo Cadence" so the UUID should be the same as what you have already set.
It is paired the PC.
The "BluetoothDataReader" Actor is added in the Level.

How can I verify that is actually connected and get some data?

Thank you in advance.

**Comment by kym0761** [comment]
Hello. I'm sorry for the late.

It's my first time getting GitHub issues.

If you paired a cadence sensor to a computer, and the Bluetooth Data Reader is present at Level,

When your cadence sensor is activated, the values in UPROPERTY() of the Bluetooth Data Reader will change.

**Comment by kym0761** [comment]
안녕하세요. 답변이 늦어서 죄송합니다. 깃허브 이슈를 받아보는게 처음이었거든요.

만약 당신이 케이던스 센서를 컴퓨터에 페어링 했고, BluetoothDataReader를 Level에 배치했다면,

당신의 케이던스 센서가 동작했을 때,(예를 들면, 흔들거나 혹은 스피닝 바이크에 부착하고 바이크를 타거나) UPROPERTY()로 된 값들이 변할 것입니다. Detail 패널에서 값이 변하는지 확인하시면 됩니다.

**Comment by kym0761** [comment]
Hello. I'm sorry for the late reply. It was my first time getting GitHub issues, so I didn't Notice it fast.

If you paired the cadence sensor to the computer and placed the "BluetoothDataReader" on the level,

When your cadence sensor is activated (e.g., shaking in front of a magnet or attaching to a spinning bike and riding it), UPROPERTY() values will change. You can check if the value changes in the Detail panel.

! edited !

And now I've confirmed that I made a mistake and I've fixed it correctly.

 - in BluetoothDataReader::ReadData(),  if( DataReceiver.IsValid()) is wrong.  if(!DataReceiver.IsValid()) is correct. -

 I think it didn't reflect on github Source because I worked it in separate SVN which used in the company.
 
Please try with fixed code.

**Comment by kym0761** [comment]
This code was made for use by the company I used to work for, but I quit the company, and I don't even have a cadence sensor right now. So I can't check if this code is working properly right now.

However, if the code is working correctly, the Unreal Engine will not crash when using it.

If the values in the Reader do not change, you can see that the "BluetoothDataReceiver"'s Run() has many if(){} for error handling. I remember that most of the problems were errors that appeared in if (S_OK!=hr) {} .

The "BluetoothDataReader" I made is just an example, so I think it would be better for you to create your own actor and use it.

If you look at the GetData() code on the "BluetoothDataReceiver", you can see how you receive data from it.

If you look at ParsingBluetoothData(), I think you can get a rough idea of how to get CSCMeasurement data.

**Comment by Besjan** [comment]
Now is working perfectly, thank you so much for your support.
